version: "3.5"  # Min version that supports our syntax (limited by networks with names).
# Don't use the latest because it's not available in GH actions.
networks:
  backend:
  frontend:
volumes:
  db-data:
  es-data:
services:

  elasticsearch:
    build: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - backend
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: logstash
    networks:
      - backend
    volumes:
      - ./data/articles:/tmp/datos:ro
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"

  kibana:
    build: kibana
    networks:
      - backend
    depends_on:
      - elasticsearch

  corpus-creator:
    build: corpus-creator
    volumes:
      - ./data/la_diaria:/data/la_diaria
      - ./data/articles:/data/articles

  qa:
    build: qa
    networks:
      - backend
    volumes:
      - ./data:/data:ro
      - ~/.cache/torch/transformers:/root/.cache/torch/transformers  # So models aren't downloaded over and over.
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - FLASK_ENV
      - FLASK_SECRET_KEY
    depends_on:
      - elasticsearch

  db:
    image: mdillon/postgis:9.6
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=covid
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - LANG=en_US.utf8
      - POSTGRES_PASSWORD

  frontend:
    build: frontend
    networks:
      - frontend
    depends_on:
      - api

  api:
    build: external-api
    networks:
      - backend
      - frontend
    environment:
      - DB_NAME=covid
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - QA_SERVER=http://qa:5000
      - DB_PASS
      - DEBUG
      - DOMAIN
      - SECRET_KEY
    depends_on:
      - db
      - qa
