# Generated by Django 3.0.5 on 2020-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.IntegerField(blank=True, choices=[(1, 'Respuesta Correcto'), (2, 'Respuesta Incorrecta'), (3, 'Noticia Falsa')], null=True),
        ),
    ]
