# Generated by Django 3.0.7 on 2021-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200504_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='feedback',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_feedback',
            field=models.IntegerField(blank=True, choices=[(1, 'Respuesta Correcta'), (2, 'Respuesta Contenida'), (3, 'Respuesta Incompleta'), (4, 'Respuesta incorrecta')], null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='paragraph_feedback',
            field=models.IntegerField(blank=True, choices=[(1, 'No relacionado'), (2, 'Relacionado'), (3, 'Contiene respuesta')], null=True),
        ),
    ]
