# Generated by Django 3.0.5 on 2020-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200504_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='prob',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.IntegerField(blank=True, choices=[(1, 'Respuesta Correcta'), (2, 'Respuesta Incorrecta'), (3, 'Noticia Falsa'), (4, 'Respuesta Parcialmente Correcta')], null=True),
        ),
    ]
