# Generated by Django 3.0.5 on 2020-05-24 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def generate_default_es_query_conf(apps, schema_editor):
    QueryConf = apps.get_model("management", "QueryConf")
    QueryConf.objects.create(
        parameter_name='ES_QUERY_CONF',
        conf=[
            {"operator": "and", "minimum_should_match": 100, "fuzziness": 1, "boost": 5},
            {"operator": "and", "minimum_should_match": 80, "fuzziness": 1, "boost": 4},
            {"operator": "and", "minimum_should_match": 60, "fuzziness": 1, "boost": 3},
            {"operator": "and", "minimum_should_match": 30, "fuzziness": 1, "boost": 3},
            {"operator": "or", "minimum_should_match": None, "fuzziness": 1, "boost": 1},
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial')
    ]
    operations = [
        migrations.RunPython(generate_default_es_query_conf)
    ]
